'use client';
import { User, X } from 'lucide-react';
import { useState } from 'react';
import type { CSSProperties } from 'react';
import type { Reservation } from '@/lib/services/schedule';

function driverName(reservation: Reservation) { const driver: any = Array.isArray(reservation.driver) ? reservation.driver[0] : reservation.driver; return reservation.driver_name || driver?.name || reservation.request?.driver_name || 'Não informado'; }
export default function ReservationDetailsButton({ reservation, className = '', timeline = false, style }: { reservation: Reservation; className?: string; timeline?: boolean; style?: CSSProperties }) {
 const [open, setOpen] = useState(false); const requester = reservation.request?.requester; const approver = reservation.request?.approver; const requesterName = requester ? `${requester.first_name || ''} ${requester.last_name || ''}`.trim() : 'Não identificado'; const approverName = approver ? `${approver.first_name || ''} ${approver.last_name || ''}`.trim() : 'Não identificado';
 return <><button type="button" onClick={() => setOpen(true)} className={className} style={style} title="Ver detalhes da reserva"><span className="block truncate">{reservation.purpose?.split(' - ')[0] || reservation.request?.event_name || 'Reserva'}</span>{timeline && <span className="block truncate text-[10px] font-normal text-blue-100">{driverName(reservation)}</span>}</button>{open && <div onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }} className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4" role="dialog" aria-modal="true"><section className="w-full max-w-lg rounded-2xl border border-[#334460] bg-[#141e2e] p-6 text-left shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-300">Reserva alocada</p><h2 className="mt-1 text-xl font-bold text-white">{reservation.request?.event_name || reservation.purpose || 'Reserva'}</h2></div><button onClick={() => setOpen(false)} aria-label="Fechar detalhes da reserva" className="rounded-lg p-2 text-slate-400 hover:bg-slate-800"><X className="size-5" /></button></div><dl className="mt-6 space-y-4 text-sm"><div><dt className="text-slate-500">Condutor</dt><dd className="mt-1 flex items-center gap-2 text-slate-200"><User className="size-4 text-emerald-400" />{driverName(reservation)}</dd></div><div><dt className="text-slate-500">Gestor responsável</dt><dd className="mt-1 text-slate-200">{approverName}</dd></div><div><dt className="text-slate-500">Retirada prevista</dt><dd className="mt-1 text-slate-200">{new Date(reservation.start_date).toLocaleString('pt-BR')}</dd></div><div><dt className="text-slate-500">Devolução prevista</dt><dd className="mt-1 text-slate-200">{new Date(reservation.end_date).toLocaleString('pt-BR')}</dd></div><div><dt className="text-slate-500">Solicitante</dt><dd className="mt-1 text-slate-200">{requesterName}</dd></div><div><dt className="text-slate-500">Preferência solicitada</dt><dd className="mt-1 text-slate-200">{reservation.request?.model_name || 'Veículo definido pelo gestor'}</dd></div></dl><div className="mt-6 flex justify-end"><button onClick={() => setOpen(false)} className="rounded-lg bg-slate-800 px-4 py-2 text-sm text-white hover:bg-slate-700">Fechar</button></div></section></div>}</>;
}
