'use client';

import { Camera, ChevronRight, ClipboardCheck, Fuel, Gauge, ImageIcon, X } from 'lucide-react';
import { useState } from 'react';

const LABELS: Record<string, string> = { limpeza: 'Limpeza interna', motor: 'Estado do motor', pneus: 'Pneus e lataria', freios: 'Freios', outros: 'Outros itens' };

function checklistEntries(checklist: unknown) {
    if (!checklist || typeof checklist !== 'object' || Array.isArray(checklist)) return [];
    return Object.entries(checklist as Record<string, any>).filter(([key, value]) => key !== 'driver_name' && value && typeof value === 'object' && !Array.isArray(value));
}

export default function VehicleActivityHistory({ checkins }: { checkins: any[] }) {
    const [selected, setSelected] = useState<any>(null);
    const [selectedImage, setSelectedImage] = useState<string | null>(null);
    const entries = selected ? checklistEntries(selected.checklist) : [];
    const photos = selected ? [...new Set([...(selected.photos || []), ...entries.map(([, value]) => value.photoUrl).filter(Boolean)])] : [];

    return <section aria-labelledby="vehicle-activity-history"><h3 id="vehicle-activity-history" className="mb-4 text-xl font-bold text-white">Histórico de atividades</h3><div className="space-y-3">{checkins?.length ? checkins.map((checkin) => <button key={checkin.id} type="button" onClick={() => setSelected(checkin)} className="flex w-full gap-4 rounded-xl border border-slate-700/50 bg-slate-800/30 p-4 text-left transition hover:border-slate-600 hover:bg-slate-800/60 focus:outline-none focus:ring-2 focus:ring-emerald-400"><div className={`mt-1 w-2 self-stretch rounded-full ${checkin.has_issues ? 'bg-amber-500' : 'bg-emerald-500'}`} /><div className="min-w-0 flex-1"><div className="flex justify-between gap-4"><span className="font-medium text-slate-100">{checkin.has_issues ? 'Devolução com apontamentos' : 'Devolução regular'}</span><span className="shrink-0 text-sm text-slate-500">{new Date(checkin.checked_in_at).toLocaleDateString('pt-BR')}</span></div><p className="mt-1 text-sm text-slate-400">Condutor: {checkin.driver_name || checkin.driver?.name || 'Não identificado'}</p><p className="mt-1 text-xs text-slate-500">{checklistEntries(checkin.checklist).length} itens verificados · {(checkin.photos || []).length || checklistEntries(checkin.checklist).filter(([, value]) => value.photoUrl).length} fotos</p></div><ChevronRight className="size-5 shrink-0 self-center text-slate-500" /></button>) : <p className="italic text-slate-500">Nenhum registro de histórico encontrado.</p>}</div>
        {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4" role="dialog" aria-modal="true" aria-labelledby="activity-details-title"><section className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-slate-700 bg-slate-900 p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><h2 id="activity-details-title" className="text-xl font-bold text-white">Detalhes dos apontamentos e devolução</h2><p className="mt-1 text-sm text-slate-400">{new Date(selected.checked_in_at).toLocaleString('pt-BR')}</p></div><button type="button" aria-label="Fechar detalhes" onClick={() => setSelected(null)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-800 hover:text-white"><X className="size-5" /></button></div>
            <div className="mt-6 grid grid-cols-1 gap-3 text-sm sm:grid-cols-3"><div className="rounded-xl border border-slate-800 bg-slate-950 p-3"><span className="text-slate-500">Condutor</span><p className="mt-1 font-medium text-slate-100">{selected.driver_name || selected.driver?.name || 'Não identificado'}</p></div><div className="rounded-xl border border-slate-800 bg-slate-950 p-3"><span className="flex items-center gap-1 text-slate-500"><Gauge className="size-3.5" />Odômetro</span><p className="mt-1 font-medium text-slate-100">{selected.odometer ?? 'Não informado'}{selected.odometer != null ? ' km' : ''}</p></div><div className="rounded-xl border border-slate-800 bg-slate-950 p-3"><span className="flex items-center gap-1 text-slate-500"><Fuel className="size-3.5" />Combustível</span><p className="mt-1 font-medium text-slate-100">{selected.fuel_level || 'Não informado'}</p></div></div>
            <div className="mt-5 rounded-xl border border-slate-800 bg-slate-950/50 p-4 text-sm"><p className="font-medium text-slate-200">Situação: <span className={selected.has_issues && !selected.resolved ? 'text-amber-300' : 'text-emerald-300'}>{selected.has_issues ? `${selected.resolved ? 'Resolvido' : 'Pendente'}${selected.alert_level ? ` · ${selected.alert_level}` : ''}` : 'Sem apontamentos'}</span></p>{(selected.return_notes || selected.repair_notes) && <p className="mt-3 whitespace-pre-wrap text-slate-300">{selected.return_notes || selected.repair_notes}</p>}</div>
            <div className="mt-5"><h3 className="flex items-center gap-2 font-semibold text-white"><ClipboardCheck className="size-5 text-emerald-400" />Checklist da devolução</h3>{entries.length ? <div className="mt-3 space-y-2">{entries.map(([key, value]) => <div key={key} className={`rounded-xl border p-3 ${value.status === 'OK' ? 'border-emerald-500/20 bg-emerald-500/5' : 'border-amber-500/30 bg-amber-500/10'}`}><div className="flex items-center justify-between gap-3"><span className="font-medium text-slate-100">{LABELS[key] || key}</span><span className={value.status === 'OK' ? 'text-xs font-semibold text-emerald-300' : 'text-xs font-semibold text-amber-300'}>{value.status === 'OK' ? 'OK' : `REVISAR${value.severity ? ` · ${value.severity}` : ''}`}</span></div>{value.notes && <p className="mt-2 whitespace-pre-wrap text-sm text-slate-300">{value.notes}</p>}{value.photoUrl && <button type="button" onClick={() => setSelectedImage(value.photoUrl)} className="mt-3 inline-flex items-center gap-2 rounded-lg border border-slate-600 px-3 py-2 text-xs font-medium text-slate-100 hover:bg-slate-800"><Camera className="size-4" />Ver foto deste item</button>}</div>)}</div> : <p className="mt-2 text-sm text-slate-500">Checklist detalhado não disponível neste registro legado.</p>}</div>
            {photos.length > 0 && <div className="mt-5"><h3 className="flex items-center gap-2 font-semibold text-white"><ImageIcon className="size-5 text-sky-300" />Fotos da devolução ({photos.length})</h3><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3">{photos.map((photo: string, index: number) => <button type="button" key={photo} onClick={() => setSelectedImage(photo)} className="overflow-hidden rounded-xl border border-slate-700 bg-slate-950 text-left focus:outline-none focus:ring-2 focus:ring-sky-300"><img src={photo} alt={`Evidência ${index + 1} da devolução`} className="aspect-square w-full object-cover" /></button>)}</div></div>}
            <button type="button" onClick={() => setSelected(null)} className="mt-6 rounded-lg bg-slate-800 px-4 py-2 text-white hover:bg-slate-700">Fechar</button></section></div>}
        {selectedImage && <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/90 p-4" role="dialog" aria-modal="true" aria-label="Foto da devolução" onClick={() => setSelectedImage(null)}><img src={selectedImage} alt="Evidência ampliada da devolução" className="max-h-full max-w-full rounded-xl object-contain" /></div>}
    </section>;
}
